### PR TITLE
Add `track.color_index` + get `tempdir` path on Windows

### PR DESCRIPTION
**Pull request by axeldelafosse**
This PR adds support for `color_index` from the Track API: https://github.com/ideoforms/AbletonOSC#track-properties.

Thank you for your hard work! I love `pylive` :) 

Edit: also added support for Windows by getting the `tempdir` path instead of using `/tmp`

### CODE REVIEW

**Review by ideoforms — CHANGES_REQUESTED** [review]
Hi there, thanks for the PR!

The `track.color_index` change looks great. 
For the `tempdir` fix:
 - `os.path.join` should be used so that no platform-specific path slashes need to be used - in fact, no platform check will then be needed at all 
 -  There should also be a symmetrical fix in `AbletonOSC` that also uses `tempdir` and os.path.join (song.py line 150)

Once that's done, I will merge both. 
Thanks again!

**Comment by axeldelafosse** [comment]
Hey,

Sorry I should have explained my decision: on macOS, `tempfile.gettempdir()` is returning `$TMPDIR` which isn't `/tmp` but in my case `/var/folders/6z/h64p3cv9283d10v7vr_s9qb80000gn/T/`. I thought that using `/tmp` on macOS would be preferable. What do you think?

Happy to make the change in `AbletonOSC` too once we agree on the best solution.

Have a nice day!

**Comment by ideoforms** [comment]
@axeldelafosse As the file is simply for transient storage, the location doesn't really matter, so long as both `AbletonOSC` and `pylive` are able to reference the same place in the fs. I've just checked, and it [appears](https://apple.stackexchange.com/questions/353832/why-is-mac-osx-temp-directory-in-weird-path) that the location given by `tempfile.gettempdir()` is consistent for different processes the same user and will stay fixed (at least for the duration of a login session...). So, it should be safe to replace `/tmp` with `tempfile.gettempdir()` for both Windows and macOS without any loss of generality. Much better solution than the existing implementation!

**Comment by axeldelafosse** [comment]
> So, it should be safe to replace /tmp with tempfile.gettempdir() for both Windows and macOS without any loss of generality

OK cool, I wasn't sure about that.

> Much better solution than the existing implementation

Agreed. Just made the changes. Thank you for the review!

**Review by ideoforms — APPROVED** [review]
👌

**Pull request merged**
